// Disposable PostgreSQL only. No hosted secrets or provider delivery.
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";
const { PGlite } = await import(pathToFileURL(process.argv[2]).href);
const db = new PGlite();
const a="11111111-1111-4111-8111-111111111111", b="22222222-2222-4222-8222-222222222222", c="33333333-3333-4333-8333-333333333333";
const g="44444444-4444-4444-8444-444444444444", venue="55555555-5555-4555-8555-555555555555", msg="66666666-6666-4666-8666-666666666666";
let checks=0;
const check = (actual, expected) => { assert.deepEqual(actual,expected); checks++; };
const rows = async sql => (await db.query(sql)).rows;
const claim = () => rows("SELECT kind,recipient_id FROM public.havato_claim_push_events(60) ORDER BY kind,recipient_id");
const clear = () => db.exec("DELETE FROM public.havato_push_events");
try {
  await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE SCHEMA auth; CREATE SCHEMA private;
    CREATE TABLE auth.users(id uuid PRIMARY KEY, verified boolean DEFAULT true);
    CREATE TABLE public.profiles(id uuid PRIMARY KEY,access_status text);
    CREATE TABLE public.businesses(id uuid PRIMARY KEY,owner_id uuid,status text);
    CREATE TABLE public.app_config(beta_launched boolean);
    CREATE TABLE public.gatherings(id uuid PRIMARY KEY,host_id uuid,status text,starts_at timestamptz,ends_at timestamptz,subject text,description text,venue_name text,neighborhood text,business_id uuid,table_id uuid);
    CREATE TABLE public.gathering_attendees(gathering_id uuid,user_id uuid,PRIMARY KEY(gathering_id,user_id));
    CREATE TABLE public.gathering_messages(id uuid PRIMARY KEY,gathering_id uuid,sender_id uuid,body text);
    CREATE TABLE public.user_blocks(blocker_id uuid,blocked_id uuid);
    CREATE FUNCTION private.is_email_verified(u uuid) RETURNS boolean LANGUAGE sql AS $$SELECT verified FROM auth.users WHERE id=u$$;
    CREATE FUNCTION public.is_beta_launched() RETURNS boolean LANGUAGE sql AS $$SELECT beta_launched FROM public.app_config$$;
    CREATE FUNCTION private.has_beta_access(u uuid) RETURNS boolean LANGUAGE sql AS $$SELECT public.is_beta_launched() AND EXISTS(SELECT 1 FROM public.profiles WHERE id=u AND access_status IN ('active','onboarded'))$$;
    CREATE FUNCTION private.venue_has_beta_access(u uuid) RETURNS boolean LANGUAGE sql AS $$SELECT public.is_beta_launched() AND EXISTS(SELECT 1 FROM public.businesses WHERE owner_id=u AND status='approved')$$;
    CREATE FUNCTION private.is_blocked_pair(a uuid,b uuid) RETURNS boolean LANGUAGE sql AS $$SELECT EXISTS(SELECT 1 FROM public.user_blocks WHERE (blocker_id=a AND blocked_id=b) OR (blocker_id=b AND blocked_id=a))$$;
    INSERT INTO auth.users(id) VALUES('${a}'),('${b}'),('${c}');
    INSERT INTO public.profiles VALUES('${a}','active'),('${b}','active'),('${c}','registered');
    INSERT INTO public.app_config VALUES(true);
    INSERT INTO public.businesses VALUES('${venue}','${c}','pending');
    INSERT INTO public.gatherings(id,host_id,status,starts_at) VALUES('${g}','${a}','approved',now()+interval '2 hours');`);
  await db.exec(await readFile(new URL("../supabase/migrations/20261003120000_havato_push_events.sql", import.meta.url),"utf8"));
  await db.exec(`INSERT INTO public.gathering_attendees VALUES('${g}','${b}')`);
  check(await claim(),[{kind:"gathering_joined",recipient_id:b}]);
  check(await claim(),[]);
  await db.exec(`UPDATE public.gatherings SET subject='private topic',description='private text' WHERE id='${g}'`);
  check(await claim(),[{kind:"gathering_updated",recipient_id:a},{kind:"gathering_updated",recipient_id:b}]);
  await db.exec(`UPDATE public.gatherings SET subject='private topic' WHERE id='${g}'`);
  check(await claim(),[]);
  await db.exec(`INSERT INTO public.gathering_messages VALUES('${msg}','${g}','${b}','secret body')`);
  check(await claim(),[{kind:"chat_message",recipient_id:a}]);
  check((await rows("SELECT * FROM public.havato_push_events")).some(e=>JSON.stringify(e).includes("secret body")),false);
  await db.exec(`UPDATE public.gatherings SET starts_at=now()+interval '30 minutes' WHERE id='${g}'`);
  await clear();
  check(await claim(),[{kind:"gathering_reminder",recipient_id:a},{kind:"gathering_reminder",recipient_id:b}]);
  check(await claim(),[]);
  await db.exec(`UPDATE public.gatherings SET starts_at=now()+interval '20 minutes' WHERE id='${g}'`);
  await db.exec("UPDATE public.havato_push_events SET claimed_at=now()");
  check(await claim(),[{kind:"gathering_reminder",recipient_id:a},{kind:"gathering_reminder",recipient_id:b}]);
  await db.exec(`UPDATE public.gatherings SET status='cancelled' WHERE id='${g}'`);
  check(await claim(),[{kind:"gathering_cancelled",recipient_id:a},{kind:"gathering_cancelled",recipient_id:b}]);
  await db.exec(`UPDATE public.businesses SET status='approved' WHERE id='${venue}'`);
  check(await claim(),[{kind:"venue_approved",recipient_id:c}]);
  await db.exec(`UPDATE public.businesses SET status='rejected' WHERE id='${venue}'`);
  check(await claim(),[{kind:"venue_rejected",recipient_id:c}]);
  await db.exec(`UPDATE public.profiles SET access_status='onboarded' WHERE id='${c}'`);
  check(await claim(),[{kind:"account_ready",recipient_id:c}]);
  await db.exec("UPDATE public.app_config SET beta_launched=false; UPDATE public.app_config SET beta_launched=true");
  check(await claim(),[a,b,c].map(recipient_id=>({kind:"account_ready",recipient_id})));
  await db.exec(`UPDATE public.gatherings SET status='approved',starts_at=now()+interval '2 hours' WHERE id='${g}'`);
  await clear();
  await db.exec(`INSERT INTO public.gathering_messages VALUES(gen_random_uuid(),'${g}','${b}','hidden'); INSERT INTO public.user_blocks VALUES('${a}','${b}')`);
  check(await claim(),[]);
  await db.exec(`DELETE FROM public.user_blocks; INSERT INTO public.gathering_messages VALUES(gen_random_uuid(),'${g}','${a}','hidden'); DELETE FROM public.gathering_attendees WHERE user_id='${b}'`);
  check(await claim(),[]);
  await db.exec(`INSERT INTO public.gathering_attendees VALUES('${g}','${b}'); UPDATE auth.users SET verified=false WHERE id='${b}'`);
  check(await claim(),[]);
  await db.exec(`UPDATE auth.users SET verified=true; UPDATE public.gatherings SET subject='changed' WHERE id='${g}'; UPDATE public.app_config SET beta_launched=false`);
  check(await claim(),[]);
  await db.exec(`UPDATE public.app_config SET beta_launched=true`); await clear();
  await db.exec(`INSERT INTO public.gathering_messages VALUES(gen_random_uuid(),'${g}','${a}','hidden'); UPDATE public.havato_push_events SET created_at=now()-interval '6 minutes'`);
  check(await claim(),[]);
  await db.exec(`UPDATE public.businesses SET status='approved' WHERE id='${venue}'; UPDATE public.businesses SET status='pending' WHERE id='${venue}'`);
  check(await claim(),[]);
  await db.exec(`UPDATE public.gatherings SET starts_at=now()-interval '1 minute' WHERE id='${g}'`); await clear();
  check(await claim(),[]);
  await assert.rejects(db.exec("SELECT public.havato_claim_push_events(0)")); checks++;
  for (const role of ["anon","authenticated"]) {
    for(const sql of ["SELECT * FROM public.havato_push_events","SELECT public.havato_claim_push_events(60)",`SELECT private.havato_push_enqueue('forged','account_ready','${a}','${a}')`]) {
      await assert.rejects(db.transaction(async tx=> { await tx.exec(`SET LOCAL ROLE ${role}`); await tx.exec(sql); })); checks++;
    }
  }
  await db.exec(`SELECT private.havato_push_enqueue('same','account_ready','${a}','${a}'); SELECT private.havato_push_enqueue('same','account_ready','${a}','${a}')`);
  check((await rows("SELECT count(*)::int AS count FROM public.havato_push_events")).at(0).count,1);
  check(await claim(),[{kind:"account_ready",recipient_id:a}]);
  check(await claim(),[]);
  const columns=(await rows("SELECT column_name FROM information_schema.columns WHERE table_name='havato_push_events' ORDER BY ordinal_position")).map(r=>r.column_name);
  check(columns,["id","event_key","kind","recipient_id","resource_id","actor_id","snapshot","created_at","expires_at","claimed_at"]);
  check((await rows("SELECT public.havato_push_event_eligible(id) AS eligible FROM public.havato_push_events")).at(0).eligible,true);
  await db.exec(`UPDATE auth.users SET verified=false WHERE id='${a}'`);
  check((await rows("SELECT public.havato_push_event_eligible(id) AS eligible FROM public.havato_push_events")).at(0).eligible,false);
  await assert.rejects(db.transaction(async tx=> { await tx.exec("SET LOCAL ROLE authenticated"); await tx.exec(`SELECT public.havato_push_event_eligible('${g}')`); })); checks++;
  await clear(); await db.exec(`UPDATE auth.users SET verified=true`);
  await db.exec(`INSERT INTO public.havato_push_events(event_key,kind,recipient_id,resource_id)
    SELECT 'batch:'||n,'account_ready','${a}','${a}' FROM generate_series(1,12) n`);
  check((await claim()).length,10); check((await claim()).length,2); check((await claim()).length,0);
  console.log(`${checks} disposable PostgreSQL event/security/scheduling checks passed`);
} finally { await db.close(); }
